markdown:       kramdown
url:            http://dmorrill10.github.io/
nav:
  -
    name:       About
    href:       /
  -
    name:       CV
    href:       cv
  -
    name:       Publications
    href:       publications
