markdown:       kramdown
url:            https://dmorrill10.github.io/
sass:
  processImport: false
nav:
  -
    name:       About
    href:       /
  -
    name:       CV
    href:       cv
  -
    name:       Publications
    href:       publications
